# -*- coding: utf-8 -*-
"""EXAMPLE CODE Q LEARNING SIMULATION

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OwNIh88iIM_Awl4b6G7e-DzdMSDpnPuV

This is an example of the code I wrote in Python to run a Q learning model to simulate consumers' choices when deciding to buy either meat or plant-based options
"""

import numpy as np
import random
import matplotlib.pyplot as plt

def diet_trans(alpha, theta, gamma, S, trials=500):
    init_value = 0
    total_score = 0
    nActions = 2 # Two options: either Plant based or meat
    Q = np.array([init_value] * nActions)
    outcomes = [(26, -5.1), (10, -0.3), (31, -1), (31, -0.0466)] #protein content and carbon emission
    std_dev = 4 # Standard deviation for outcomes
    choices = []
    PEs = []
    choice_plant_based = np.zeros(trials)
    choice_meat = np.zeros(trials)

    for i in range(trials):
        probs = np.power(np.e, theta * Q)
        probs /= sum(probs) # Normalize probabilities
        choice = np.nonzero(random.random() < np.cumsum(probs))[0][0]
        outcome = random.gauss(outcomes[choice][0], std_dev)
        total_score += outcome

        if choice == 0:
            choice_meat[i] = 1
        else:
            choice_meat[i] = 0

        if choice == 1:
            choice_plant_based[i] = 1
        else:
            choice_plant_based[i] = 0

        choices.append(choice)
        # Calculate prediction error
        prediction_error = outcome - Q[choice]
        PEs.append(np.abs(prediction_error)) # Absolute prediction error
        # Update Q-value and alpha
        Q[choice] = Q[choice] + S * alpha * prediction_error
        alpha = gamma * (np.abs(prediction_error) / max(PEs)) + ((1 - gamma) * alpha)

    return (Q, total_score, choice_plant_based, choice_meat)

"""simulation, by changing learning rate parameter and temperature, the agent explores the environment more and more."""

random.seed(2)
# Define parameters
alpha = 0.1 #learning rate
theta = 0.1 #temperature
gamma = 0.5
S = 0.5
# Run the simulation
results = diet_trans(alpha, gamma, S, theta)

# Print results (you can add more analysis)
print("alpha = 0.1, theta = 0.1, gamma = 0.5, S = 0.5")
print("Q values: ", results[0])
print("Total Score: ", results[1], "\n")
# Plot choice ratios over trials
width = 10
result_meat = results[2][:(len(results[2]) // width) *width].reshape(-1, width).mean(axis=1)
result_plant_based = results[3][:(len(results[3]) // width) *width].reshape(-1, width).mean(axis=1)
plt.plot(result_meat, label="Meat Option")
plt.plot(result_plant_based, label="Plant-based")
plt.legend()
plt.ylabel("Choice Ratio")
plt.xlabel("Trials (x 10)")
plt.show()

random.seed(2)
# Define parameters
alpha = 0.5 #learning rate
theta = 0.5 #temperature
gamma = 0.1
S = 0.5
# Run the simulation
results = diet_trans(alpha, gamma, S, theta)

# Print results (you can add more analysis)
print("alpha = 0.5, theta = 0.5, gamma = 0.5, S = 0.5")
print("Q values: ", results[0])
print("Total Score: ", results[1], "\n")
# Plot choice ratios over trials
width = 10
result_meat = results[2][:(len(results[2]) // width) *width].reshape(-1, width).mean(axis=1)
result_plant_based = results[3][:(len(results[3]) // width) *width].reshape(-1, width).mean(axis=1)
plt.plot(result_meat, label="Meat Option")
plt.plot(result_plant_based, label="Plant-based")
plt.legend()
plt.ylabel("Choice Ratio")
plt.xlabel("Trials (x 10)")
plt.show()